CREATE TABLE posts (
    id BIGINT(20) UNSIGNED AUTO_INCREMENT NOT NULL,
    user_id BIGINT(20) UNSIGNED NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME,
    PRIMARY KEY (id),
    CONSTRAINT fk_posts_user_id FOREIGN KEY (user_id) REFERENCES users(id)
) CHARACTER SET 'utf8mb4'
  COLLATE 'utf8mb4_general_ci';
