ALTER TABLE posts ADD COLUMN user_id BIGINT(20) UNSIGNED NOT NULL AFTER id;
ALTER TABLE posts ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE posts DROP COLUMN author;
