[package]
name = "patic"
version = "0.1.0"
authors = ["ParkSB <parkgds@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-rt = "1"
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
diesel = { version = "1.4", features = ["mysql", "chrono"]}
