name: ReasonML Client CI

on:
  push:
    branches:
      - master
    paths:
      - 'client/reasonml/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - master
    paths:
      - 'client/reasonml/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client/reasonml && npm install && npm run build
