name: Client CI

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - master
    paths:
      - 'client/**'
      - '.github/workflows/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && cargo install cargo-make && cargo make check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && cargo install cargo-make && cargo make test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && cargo install cargo-make && cargo make build
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && cargo clippy --verbose
