name: TypeScript Client CI

on:
  push:
    branches:
      - master
    paths:
      - 'client/typescript/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - master
    paths:
      - 'client/typescript/**'
      - '.github/workflows/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client/typescript && npm install && npm run check
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client/typescript && npm install && npm run build
