name: Server CI

on:
  push:
    branches:
      - master
    paths:
      - 'server/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - master
    paths:
      - 'server/**'
      - '.github/workflows/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd server && cargo check --verbose
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd server && cargo test --verbose
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd server && cargo build --verbose --release
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd server && cargo clippy --verbose
