name: Client CI

on:
  push:
    branches:
      - master
      - development
    paths:
      - 'client/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - master
      - development
    paths:
      - 'client/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./client
    steps:
      - uses: actions/checkout@v2
      - name: install
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm install
      - name: check
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run check
      - name: build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run build
