name: API Gateway CI

on:
  push:
    branches:
      - master
      - development
    paths:
      - 'api-gateway/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - master
      - development
    paths:
      - 'api-gateway/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./api-gateway
    steps:
      - uses: actions/checkout@v2
      - name: fmt
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: cargo fmt -- --check
      - name: clippy
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: cargo clippy --verbose
      - name: test
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: cargo test --verbose
      - name: check
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: cargo check --verbose
      - name: build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: cargo build --verbose --release
